####################################################################
#  GitHub Action to perform snapshot artifact creation
#####################################################################
name: 'Liquibase Pro Artifact Creation'

on:
  push:
    branches:
      - 'develop'

#env:
#
#  # AWS S3 bucket is the host part of the S3 bucket
#  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
#  # AWS Access credentials
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
#
#  # Default AWS region
#  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  ####################################################################
  #  Initialization
  ####################################################################
  init:
    runs-on: [self-hosted]
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  ###################################################################
  #  Check out the source code
  ####################################################################
  checkout-repo:
    runs-on: [self-hosted]

    steps:
      # Check out the source code
      - name: Checkout repo
        uses: actions/checkout@v3

  ####################################################################
  #  Create the artifact
  #####################################################################
  create-artifact:
    needs: [checkout-repo, init]
    runs-on: [self-hosted]

    steps:
      # Show archive source
      - name: Show archive source
        run: |
          pwd; ls -l

      # Zip the source into a versioned release file
      - name: Zip the Release
        run: zip -r SNAPSHOT-artifact-${{ github.run_id }}.${{ github.run_number }}.zip .

      # Upload the file to S3
      - name: Upload Release to s3
        run: |
          aws s3 cp SNAPSHOT-artifact-${{ github.run_id }}.${{ github.run_number }}.zip s3://$AWS_S3_BUCKET
